spring:
  datasource:
    url: jdbc:mysql://47.98.186.65:3306/uaa?useUnicode=true&characterEncoding=UTF8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    # innodb
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8080

logging:
  level:
    root: info